# Generated by Django 5.2.17 on 2026-10-03 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_menu_id_rubrique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=255)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('rubrique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navigations', to='application.rubrique')),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
