# Generated by Django 5.2.17 on 2026-10-07 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_remove_navigation_url_navigation_slug_sousnavigation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('img', models.CharField(blank=True, max_length=500)),
                ('lien', models.CharField(blank=True, max_length=500)),
                ('type', models.CharField(default='content', max_length=50)),
                ('rubrique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='application.rubrique')),
            ],
        ),
    ]
